name: First Workflow

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Salutation
        run: 
          echo "Hello World"
